include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    always_declare_return_types: true
    avoid_unnecessary_containers: true
    prefer_final_fields: true
    unnecessary_string_interpolations: true

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
